### ISSUE TITLE
Problems in share and post a survey on an external web site

### ISSUE THREAD

**Issue by SerenaTWS** [ForceDotComLabs/survey-force#24]
We installed Survey Force in our Salesforce's sandbox starting from the Appexchange market.
We created a first sample survey to test the tool and then we also tried to public it on the company's web site (an external site, not the salesforce's web site).
To do that we created a force.com site and we added permission to the visualforce pages: 
 “Take Survey”  and “labs_survey_css”  as stated in the installation guide https://appexchange.salesforce.com/servlet/servlet.FileDownload?file=00P3000000P3P4XEAV.
We also tried to add the apex classes: AddUsersController”, 
“ViewSurveyController” and  
“SurveyAndQuestionController” into the “Enabled Apex Classes” section. but we can't find the AddUsersController.
Even if we hadn't the first apex class, we saved the changes and tried to use the web site but as expected it didn't work (when we click on the salesforce's urls site a page with the button submit appears, but without the survey).
I think there is something wrong in the setting up of the force.com site such as  the home page, the rights of access (we created it just to visualize the survey and allow external sobject to take it).

Could you please help me?

**Comment by coriobrien** [comment]
I'm having this same issue. Has anyone been able to comment?
[Survey Error.docx](https://github.com/ForceDotComLabs/survey-force/files/287221/Survey.Error.docx)
